baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Recomet AB'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/recomet-o.svg"
  desktop: "images/logo/recomet-logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: ''

seo:
  meta_og_title: "Recomet AB"
  meta_og_type: "website"
  meta_og_url: "https://recomet.se/"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Recomet AB is specialized in solving your wastewater challenges by consulting, supply of know how and processes and turnkey installations."

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
